name: Latest worked metrics workflow

on:
  schedule:
    # Runs every ten minutes
    - cron: '*/10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"

      - name: Update activity from AniList
        uses: RangerDigital/neko-box@master
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          ANILIST_USERNAME: ${{ secrets.ANILIST_USERNAME }}
